# Identificação do projeto
sonar.projectKey=jokenpoke-backend
sonar.projectName=JokenPoke Backend
sonar.projectVersion=1.0

# Fontes
sonar.sources=app
sonar.tests=tests

# Cobertura de testes
sonar.python.coverage.reportPaths=reports/coverage.xml

# Relatório de testes
sonar.python.xunit.reportPath=reports/test-results.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusões
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**